kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: http-server
    nodePort: 30014
  selector:
    app: guestbook
